name: publish
on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
    paths:
      - "Dockerfile"
      - "requirements.txt"
      - "app/**"
  workflow_dispatch: {}


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute tags
        id: meta
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          SHORT_SHA=${GITHUB_SHA::7}
          REF=${GITHUB_REF_NAME}
          echo "tags=${IMAGE}:latest,${IMAGE}:${SHORT_SHA},${IMAGE}:${REF}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
